[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/f7dd0d25224849aba674dd02d7452719"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
